# Generated by Django 6.0.8 on 2026-08-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_lostandfound_remove_founditem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
