# Generated by Django 6.0.8 on 2026-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_accommodation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
    ]
